name: backend test

on:
  push:
    branches: ["backendFinal", "CalendarRequestRoutes"]
  pull_request:
    branches: ["backendFinal", "CalendarRequestRoutes"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup packages
        uses: actions/setup-python@v2
      - name: Install packages
        run: pip install -r backend/requirements.txt
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run Tests
        run: python -m pytest -vv backend/
      - name: Install pylint
        run: pip install pylint
      - name: Run Lint
        run: pylint backend
